import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const eslintConfig = [
  { ignores: ["**/.next/**", "next-env.d.ts", ".claude/worktrees/**"] }, // next-env.d.ts is auto-generated by Next.js; "This file should not be edited". ".next/**" alone didn't catch nested worktree builds under .claude/worktrees/*/.next
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
