import {
  IconReact,
  IconNextjs,
  IconTypeScript,
  IconVue,
  IconShadcn,
  IconSass,
  IconRedux,
  IconReduxSaga,
  IconReactHookForm,
  IconZod,
  IconTailwindCss,
  IconI18next,
  IconAxios,
  IconSocketIo,
  IconNodejs,
  IconZustand,
  IconJotai,
  IconYup,
  IconFormik,
  IconTanStack,
  IconApexCharts,
  IconFirebase,
  IconStorybook,
  IconTestingLibrary,
  IconGit,
  IconBootstrap,
  IconAntDesign,
  IconAos,
  IconMui,
} from "@/components/icons";
import type { TechBadge } from "@/features/portfolio/types/content";

export const TECH_BADGE_STAGGER_DELAY_SECONDS = 0.05;

export const techStack: TechBadge[] = [
  {
    name: "React",
    Icon: IconReact,
    bg: "#20232a",
    fg: "#61dafb",
    url: "https://react.dev",
  },
  {
    name: "Next.js",
    Icon: IconNextjs,
    bg: "#12141a",
    fg: "#ffffff",
    url: "https://nextjs.org",
  },
  {
    name: "TypeScript",
    Icon: IconTypeScript,
    bg: "#2b5f9e",
    fg: "#ffffff",
    url: "https://www.typescriptlang.org",
  },
  {
    name: "Vue.js",
    Icon: IconVue,
    bg: "#4fc08d",
    fg: "#ffffff",
    url: "https://vuejs.org",
  },
  {
    name: "Shadcn/ui",
    Icon: IconShadcn,
    bg: "#000000",
    fg: "#ffffff",
    url: "https://ui.shadcn.com",
  },
  {
    name: "Sass/CSS",
    Icon: IconSass,
    bg: "#cc6699",
    fg: "#ffffff",
    url: "https://sass-lang.com",
  },
  {
    name: "Redux Toolkit",
    Icon: IconRedux,
    bg: "#764abc",
    fg: "#ffffff",
    url: "https://redux-toolkit.js.org",
  },
  {
    name: "Redux Saga",
    Icon: IconReduxSaga,
    bg: "#999999",
    fg: "#ffffff",
    url: "https://redux-saga.js.org",
  },
  {
    name: "React Hook Form",
    Icon: IconReactHookForm,
    bg: "#ec5990",
    fg: "#ffffff",
    url: "https://react-hook-form.com",
  },
  {
    name: "Zod",
    Icon: IconZod,
    bg: "#408aff",
    fg: "#ffffff",
    url: "https://zod.dev",
  },
  {
    name: "Tailwind",
    Icon: IconTailwindCss,
    bg: "#0ea5e9",
    fg: "#062a3d",
    url: "https://tailwindcss.com",
  },
  {
    name: "i18n",
    Icon: IconI18next,
    bg: "#26a69a",
    fg: "#ffffff",
    url: "https://www.i18next.com",
  },
  {
    name: "Axios",
    Icon: IconAxios,
    bg: "#5a29e4",
    fg: "#ffffff",
    url: "https://axios-http.com",
  },
  {
    name: "Socket.IO",
    Icon: IconSocketIo,
    bg: "#010101",
    fg: "#ffffff",
    url: "https://socket.io",
  },
  {
    name: "Node.js",
    Icon: IconNodejs,
    bg: "#5fa04e",
    fg: "#ffffff",
    url: "https://nodejs.org",
  },
  {
    name: "Zustand",
    Icon: IconZustand,
    bg: "#7c5832",
    fg: "#ffffff",
    url: "https://zustand.docs.pmnd.rs",
  },
  {
    name: "Jotai",
    Icon: IconJotai,
    bg: "#2b6cb0",
    fg: "#ffffff",
    url: "https://jotai.org",
  },
  {
    name: "Yup",
    Icon: IconYup,
    bg: "#16a34a",
    fg: "#ffffff",
    url: "https://github.com/jquense/yup",
  },
  {
    name: "Formik",
    Icon: IconFormik,
    bg: "#2563eb",
    fg: "#ffffff",
    url: "https://formik.org",
  },
  {
    name: "TanStack Query",
    Icon: IconTanStack,
    bg: "#ff4154",
    fg: "#ffffff",
    url: "https://tanstack.com/query/latest",
  },
  {
    name: "RTK Query",
    Icon: IconRedux,
    bg: "#764abc",
    fg: "#ffffff",
    url: "https://redux-toolkit.js.org/rtk-query/overview",
  },
  {
    name: "ApexCharts",
    Icon: IconApexCharts,
    bg: "#008ffb",
    fg: "#ffffff",
    url: "https://apexcharts.com",
  },
  {
    name: "Firebase",
    Icon: IconFirebase,
    bg: "#dd2c00",
    fg: "#ffffff",
    url: "https://firebase.google.com",
  },
  {
    name: "Storybook",
    Icon: IconStorybook,
    bg: "#ff4785",
    fg: "#ffffff",
    url: "https://storybook.js.org",
  },
  {
    name: "Testing Library",
    Icon: IconTestingLibrary,
    bg: "#e33332",
    fg: "#ffffff",
    url: "https://testing-library.com",
  },
  {
    name: "Git",
    Icon: IconGit,
    bg: "#f05033",
    fg: "#ffffff",
    url: "https://git-scm.com",
  },
  {
    name: "Bootstrap",
    Icon: IconBootstrap,
    bg: "#7952b3",
    fg: "#ffffff",
    url: "https://getbootstrap.com",
  },
  {
    name: "Ant Design",
    Icon: IconAntDesign,
    bg: "#0170fe",
    fg: "#ffffff",
    url: "https://ant.design",
  },
  {
    name: "AOS",
    Icon: IconAos,
    bg: "#6b46c1",
    fg: "#ffffff",
    url: "https://michalsnik.github.io/aos/",
  },
  {
    name: "Material UI",
    Icon: IconMui,
    bg: "#007fff",
    fg: "#ffffff",
    url: "https://mui.com",
  },
  { name: "Meteor", Icon: null },
  { name: "MongoDB", Icon: null },
  { name: "Stripe", Icon: null },
];
