import {
  IconReact,
  IconNextjs,
  IconTypeScript,
  IconVue,
  IconShadcn,
  IconSass,
  IconRedux,
  IconReduxSaga,
  IconReactHookForm,
  IconZod,
  IconTailwindCss,
  IconI18next,
  IconAxios,
  IconSocketIo,
  IconNodejs,
  IconZustand,
  IconJotai,
  IconYup,
  IconFormik,
  IconTanStack,
  IconApexCharts,
  IconFirebase,
  IconStorybook,
  IconTestingLibrary,
  IconGit,
  IconBootstrap,
  IconAntDesign,
  IconAos,
  IconMui,
} from "@/components/icons";
import type { TechBadge } from "@/features/portfolio/types/content";

export const TECH_BADGE_STAGGER_DELAY_SECONDS = 0.05;

export const techStack: TechBadge[] = [
  { name: "React", Icon: IconReact, bg: "#20232a", fg: "#61dafb" },
  { name: "Next.js", Icon: IconNextjs, bg: "#12141a", fg: "#ffffff" },
  { name: "TypeScript", Icon: IconTypeScript, bg: "#2b5f9e", fg: "#ffffff" },
  { name: "Vue.js", Icon: IconVue, bg: "#4fc08d", fg: "#ffffff" },
  { name: "Shadcn/ui", Icon: IconShadcn, bg: "#000000", fg: "#ffffff" },
  { name: "Sass/CSS", Icon: IconSass, bg: "#cc6699", fg: "#ffffff" },
  { name: "Redux Toolkit", Icon: IconRedux, bg: "#764abc", fg: "#ffffff" },
  { name: "Redux Saga", Icon: IconReduxSaga, bg: "#999999", fg: "#ffffff" },
  { name: "React Hook Form", Icon: IconReactHookForm, bg: "#ec5990", fg: "#ffffff" },
  { name: "Zod", Icon: IconZod, bg: "#408aff", fg: "#ffffff" },
  { name: "Tailwind", Icon: IconTailwindCss, bg: "#0ea5e9", fg: "#062a3d" },
  { name: "i18n", Icon: IconI18next, bg: "#26a69a", fg: "#ffffff" },
  { name: "Axios", Icon: IconAxios, bg: "#5a29e4", fg: "#ffffff" },
  { name: "Socket.IO", Icon: IconSocketIo, bg: "#010101", fg: "#ffffff" },
  { name: "Node.js", Icon: IconNodejs, bg: "#5fa04e", fg: "#ffffff" },
  { name: "Zustand", Icon: IconZustand, bg: "#7c5832", fg: "#ffffff" },
  { name: "Jotai", Icon: IconJotai, bg: "#2b6cb0", fg: "#ffffff" },
  { name: "Yup", Icon: IconYup, bg: "#16a34a", fg: "#ffffff" },
  { name: "Formik", Icon: IconFormik, bg: "#2563eb", fg: "#ffffff" },
  { name: "TanStack Query", Icon: IconTanStack, bg: "#ff4154", fg: "#ffffff" },
  { name: "RTK Query", Icon: IconRedux, bg: "#764abc", fg: "#ffffff" },
  { name: "ApexCharts", Icon: IconApexCharts, bg: "#008ffb", fg: "#ffffff" },
  { name: "Firebase", Icon: IconFirebase, bg: "#dd2c00", fg: "#ffffff" },
  { name: "Storybook", Icon: IconStorybook, bg: "#ff4785", fg: "#ffffff" },
  { name: "Testing Library", Icon: IconTestingLibrary, bg: "#e33332", fg: "#ffffff" },
  { name: "Git", Icon: IconGit, bg: "#f05033", fg: "#ffffff" },
  { name: "Bootstrap", Icon: IconBootstrap, bg: "#7952b3", fg: "#ffffff" },
  { name: "Ant Design", Icon: IconAntDesign, bg: "#0170fe", fg: "#ffffff" },
  { name: "AOS", Icon: IconAos, bg: "#6b46c1", fg: "#ffffff" },
  { name: "Material UI", Icon: IconMui, bg: "#007fff", fg: "#ffffff" },
];
